### ISSUE TITLE
图片名称包含空格时转换失败

### ISSUE THREAD

**Issue by KoalaMini** [cocowool/hexo-image-link#2]
![图片](https://user-images.githubusercontent.com/80962299/124720884-2e6ea600-df3b-11eb-8196-bafcac3821a5.png)

**Comment by damengzhang** [comment]
可以先使用 typora 转义路径来解决这个问题：

![image](https://user-images.githubusercontent.com/22831550/147765006-f4102e89-92a6-41a1-a309-e80ce898fd00.png)

**Comment by cocowool** [comment]
Fix the problem that filename contains space, Please try again.
修正了不支持文件名中有空格的场景
